/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Juego;

import botones.botonReiniciar;
import botones.botonSalir;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author samuelson
 */
public class EndScreen extends javax.swing.JFrame {

    /**
     * Creates new form Victoria
     */
    public EndScreen() {
        initComponents();
        setLocationRelativeTo(null);
      
    }
    public void Derrota(){
        Dimension dimension = new Dimension(852,480);
        this.setMaximumSize(dimension);
        this.setPreferredSize(dimension);
        this.setSize(dimension);
        this.setMaximumSize(dimension);
        this.repaint();
        JLabel gameOver = new JLabel();
        gameOver.setIcon(new ImageIcon(getClass().getClassLoader().getResource("gameOver.jpg")));
        gameOver.setSize(dimension);
        gameOver.setLocation(0,0);
        botonSalir salir = new botonSalir(this);
        salir.setLocation(200, 400);
        botonReiniciar reiniciar = new botonReiniciar(this);
        reiniciar.setLocation(450, 400);
        gameOver.add(reiniciar);
        gameOver.add(salir);
        this.setLocationRelativeTo(null);
        this.add(gameOver);
        
    }
    
    public void victoria(){
        Dimension dimension = new Dimension(852,480);
        
        this.setMaximumSize(dimension);
        this.setPreferredSize(dimension);
        this.setSize(dimension);
        this.setMaximumSize(dimension);
        this.setBackground(Color.WHITE);
        JLabel gameOver = new JLabel();
        gameOver.setIcon(new ImageIcon(getClass().getClassLoader().getResource("youWin.png")));
        gameOver.setSize(dimension);
        gameOver.setBackground(Color.WHITE);
        gameOver.setLocation(201,0);
        botonSalir salir = new botonSalir(this);
        salir.setLocation(0, 400);
        botonReiniciar reiniciar = new botonReiniciar(this);
        reiniciar.setLocation(230, 400);
        gameOver.add(reiniciar);
        gameOver.add(salir);
        this.setLocationRelativeTo(null);
        this.add(gameOver);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
