/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Juego;

import botones.botonJugar;
import botones.botonOpciones;
import botones.botonSalirMain;
import javax.swing.ImageIcon;

/**
 *
 * @author samuelson
 */
public class Menu extends javax.swing.JFrame {

    private int cantidadDiscos = 3;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        menu.setVisible(true);
        setLocationRelativeTo(null);
        botonJugar jugar = new botonJugar(this);
        jugar.setLocation(75, 170);
        botonOpciones opciones = new botonOpciones(this);
        opciones.setLocation(300, 170);
        botonSalirMain salir = new botonSalirMain(this);
        salir.setLocation(525, 170);
        jLabel1.add(jugar);
        jLabel1.add(opciones);
        jLabel1.add(salir);
        setVisible(true);
//         Interfaz interfaz = new Interfaz();
//        interfaz.iniciar(jSlider1.getValue());
//        interfaz.setVisible(true);
//        this.dispose();
//        jLabel2.setText(jSlider1.getValue()+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(768, 343));
        setMinimumSize(new java.awt.Dimension(768, 343));
        setPreferredSize(new java.awt.Dimension(768, 343));
        getContentPane().setLayout(new java.awt.CardLayout());

        menu.setBackground(new java.awt.Color(204, 255, 255));
        menu.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new ImageIcon(getClass().getClassLoader().getResource("Interfaz/FondoMenu.png"))
        );
        menu.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(menu, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }

    public int getCantidadDiscos() {
        return cantidadDiscos;
    }

    public void setCantidadDiscos(int cantidadDiscos) {
        this.cantidadDiscos = cantidadDiscos;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}


