/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Movimientos;

import java.awt.Color;

/**
 *
 * @author phily
 */
public class limiteMovimientos extends javax.swing.JLabel {

    int movimientos = 0;

    /**
     * Creates new form limiteMovimientos
     */
    public limiteMovimientos() {
        initComponents();
    }

    public void establecerDatos(int discos) {
        movimientos = discos;
        lbl_restantes.setText((int) (Math.pow(2, discos) - 1) + "");
        lbl_restantes.updateUI();

    }

    public void disminuirOportunidades() {
        lbl_restantes.setText(String.valueOf(movimientos--));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_restantes = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(100, 30));
        setMinimumSize(new java.awt.Dimension(100, 30));
        setPreferredSize(new java.awt.Dimension(100, 30));

        lbl_restantes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbl_restantes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_restantes.setMaximumSize(new java.awt.Dimension(100, 30));
        lbl_restantes.setMinimumSize(new java.awt.Dimension(100, 30));
        lbl_restantes.setOpaque(true);
        lbl_restantes.setPreferredSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_restantes, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_restantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_restantes;
    // End of variables declaration//GEN-END:variables
}
