/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Movimientos;

/**
 *
 * @author samuelson
 */
public class Limite extends javax.swing.JLabel {
    int movimientos;
    /**
     * Creates new form Limite
     */
    public Limite() {
        initComponents();
        
    }
    public void establecerDatos(int discos) {
        movimientos = discos;
        setText(calcular(discos) + "");
        updateUI();

    }
    public int calcular(int discos){
        return (int) (Math.pow(2, discos) - 1);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setFont(new java.awt.Font("Chilanka", 1, 24)); // NOI18N
        setForeground(new java.awt.Color(255, 255, 255));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
