/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Movimientos;

import java.awt.Color;

/**
 *
 * @author phily
 */
public class limiteMovimientos extends javax.swing.JPanel {
    int movimientos=0;        
    
    /**
     * Creates new form limiteMovimientos
     */
    public limiteMovimientos() {
        initComponents();
    }

    public void establecerDatos(int numeroMovimientos){        
        movimientos = numeroMovimientos;
        lbl_restantes.setText(String.valueOf(movimientos));         
        this.setVisible(true);
    }
    
    public void disminuirOportunidades(){
        lbl_restantes.setText(String.valueOf(movimientos--));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_restantes = new javax.swing.JLabel();

        jLabel1.setBackground(new java.awt.Color(220, 206, 223));
        jLabel1.setFont(new java.awt.Font("Sawasdee", 1, 17)); // NOI18N
        jLabel1.setText("MOVIMIENTOS");
        jLabel1.setOpaque(true);

        lbl_restantes.setBackground(new java.awt.Color(238, 208, 221));
        lbl_restantes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_restantes.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_restantes, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_restantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_restantes;
    // End of variables declaration//GEN-END:variables
}
